### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Prowl'

### ISSUE THREAD

**Issue by hostingnuggets** [toddrob99/pyprowl#5]
Trying out your example code unfortunately does not work for me, as you can see below from the output:

```
Traceback (most recent call last):
  File "p.py", line 3, in <module>
    p = pyprowl.Prowl('MY_KEY')
AttributeError: 'module' object has no attribute 'Prowl'
```

I installed the module with `sudo pip install pyprowl` and am using Python 2.7.16 on Raspbian 10 (buster).

**Comment by toddrob99** [comment]
Can you paste more of your code please?

**Comment by hostingnuggets** [comment]
That's the code I am using:

```
import pyprowl

p = pyprowl.Prowl('MY_KEY')

try:
	p.verify_key()
	print "Prowl API key successfully verified!"
except Exception, e:
	print "Error verifying Prowl API key:",e
	exit()

try:
	p.notify('Event name', 'Description of event', 
			 priority=0, url='http://www.example.com', appName='Name of app sending the notification')
	print "Notification successfully sent to Prowl!"
except Exception, e:
	print "Error sending notification to Prowl:",e
```

**Comment by toddrob99** [comment]
This is due to the way I created the package for pypi. I will need to move the contents of pyprowl.py to __init__.py. I guess you’re the first to try using it as an imported module—I’ve only used it so far by including a copy of pyprowl.py within my other package. 

I’m on vacation this week, so it will probably be next week by the time I can sit at my computer long enough to fix and publish a new version to pypi. Sorry for the inconvenience.

**Comment by hostingnuggets** [comment]
But I just copied your code 1:1 under `Usage` from your https://github.com/toddrob99/pyprowl/blob/master/README.md file, so I don't understand how I am the first one trying to import this module? 

Thanks for fixing, would be great that your example code under usage works.

**Comment by toddrob99** [comment]
The sample code works for me, but that’s because I run it from the folder where pyprowl.py is located. When I changed the package structure for pypi, I skipped a step and therefore it doesn’t work when installed through pip. I guess no one else has used this module at all—I wrote it for personal use and only published to pypi recently.

**Comment by hostingnuggets** [comment]
I see thank you very much for your fast answer! Well I think your module is very useful and simple to use so I will use it as soon as fixed ;-)

**Comment by toddrob99** [comment]
Please update to v1.0.2 and let me know if you are able to use the package. `pip install --upgrade pyprowl`

**Comment by hostingnuggets** [comment]
Thank you, it works now!
